# Generated by Django 5.2.1 on 2025-06-09 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_remove_event_address_remove_event_seats_available_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={},
        ),
    ]
