# Generated by Django 5.2.1 on 2025-06-07 06:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('type', models.CharField(choices=[('event_reminder', 'Напоминание о мероприятии'), ('booking_confirmation', 'Подтверждение бронирования'), ('event_cancelled', 'Мероприятие отменено'), ('event_updated', 'Мероприятие обновлено')], default='event_reminder', max_length=32)),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('read', 'Прочитано'), ('failed', 'Ошибка отправки')], default='pending', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('related_event', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='events.event')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
