# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: notyfy.proto
# Protobuf Python Version: 6.31.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    0,
    '',
    'notyfy.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0cnotyfy.proto\x12\x14notification_service\"\x81\x01\n\x0cNotification\x12\n\n\x02id\x18\x01 \x01(\x05\x12\x0f\n\x07user_id\x18\x02 \x01(\x05\x12\x34\n\x04type\x18\x03 \x01(\x0e\x32&.notification_service.NotificationType\x12\r\n\x05title\x18\x04 \x01(\t\x12\x0f\n\x07message\x18\x05 \x01(\t\"r\n\x14NotificationResponse\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x0f\n\x07message\x18\x02 \x01(\t\x12\x38\n\x0cnotification\x18\x03 \x01(\x0b\x32\".notification_service.Notification*h\n\x10NotificationType\x12\x12\n\x0e\x45VENT_REMINDER\x10\x00\x12\x18\n\x14\x42OOKING_CONFIRMATION\x10\x01\x12\x13\n\x0f\x45VENT_CANCELLED\x10\x02\x12\x11\n\rEVENT_UPDATED\x10\x03\x32{\n\x12NotificationSender\x12\x65\n\x11send_notification\x12\".notification_service.Notification\x1a*.notification_service.NotificationResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'notyfy_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_NOTIFICATIONTYPE']._serialized_start=286
  _globals['_NOTIFICATIONTYPE']._serialized_end=390
  _globals['_NOTIFICATION']._serialized_start=39
  _globals['_NOTIFICATION']._serialized_end=168
  _globals['_NOTIFICATIONRESPONSE']._serialized_start=170
  _globals['_NOTIFICATIONRESPONSE']._serialized_end=284
  _globals['_NOTIFICATIONSENDER']._serialized_start=392
  _globals['_NOTIFICATIONSENDER']._serialized_end=515
# @@protoc_insertion_point(module_scope)
