[project]
name = "simple_grpc_server"
version = "0.1.0"
description = "grpc server for debug"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "grpcio>=1.73.0",
    "grpcio-tools>=1.73.0",
]
